####################################################
# DVrouter.py
# Name:
# HUID:
#####################################################

import json
from router import Router


class DVrouter(Router):
    """Distance vector routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # add your own class fields and initialization code here

        #Links to direct neighbors
        self.neighbor_links = {}

        #Distance Vector tracking
        self.dv = {self.addr: {self.addr: 0}}

        #Forwarding table
        self.forwarding_table = {}

    def _update_routing_table(self):
        """Recalculate the minimum costs and update the forwarding table using Bellman-Ford."""
        old_dv_self = self.dv.get(self.addr, {}).copy()

        # Reset our own vector safely using a temporary tracking structure
        new_dv_self = {self.addr: 0}
        new_forwarding_table = {self.addr: None}

        # Find all possible destinations known to this router or any neighbor
        all_destinations = set()
        for node, routes in self.dv.items():
            all_destinations.update(routes.keys())
        
        # Also consider direct neighbor destinations
        for port, (neighbor, link_cost) in self.neighbor_links.items():
            all_destinations.add(neighbor)

        for dst in all_destinations:
            if dst == self.addr:
                continue

            min_cost = float('inf')
            best_port = None

            # Check costs through each of our directly connected neighbor links
            for port, (neighbor, link_cost) in self.neighbor_links.items():
                # Direct link path fallback
                if dst == neighbor:
                    if link_cost < min_cost:
                        min_cost = link_cost
                        best_port = port

                # If the neighbor knows a path to the destination
                if neighbor in self.dv and dst in self.dv[neighbor]:
                    cost_through_neighbor = link_cost + self.dv[neighbor][dst]
                    if cost_through_neighbor < min_cost:
                        min_cost = cost_through_neighbor
                        best_port = port

            # If a valid path is found, update our vector and forwarding table
            if min_cost < float('inf'):
                new_dv_self[dst] = min_cost
                new_forwarding_table[dst] = best_port

        self.dv[self.addr] = new_dv_self
        self.forwarding_table = new_forwarding_table

        # Check if our own distance vector changed. If so, broadcast to neighbors.
        if self.dv[self.addr] != old_dv_self:
            self._broadcast_dv()

    def _broadcast_dv(self):
        """Send the current router's distance vector to all connected neighbors."""
        # The packet payload is just our own distance vector dictionary: {dst: cost}
        # Converted to a string representation to satisfy the simulator's type requirements
        packet_content = json.dumps(self.dv[self.addr])

        for port in self.neighbor_links.keys():
            # Create a routing packet
            from packet import Packet
            pkt = Packet(kind=Packet.ROUTING, src_addr=self.addr, dst_addr=None, content=packet_content)
            self.send(port, pkt)

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        from packet import Packet
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            # send packet based on forwarding table, e.g., self.send(port, packet)

            # Forward it along if we have a route
            if packet.dst_addr in self.forwarding_table:
                next_port = self.forwarding_table[packet.dst_addr]
                if next_port is not None:
                    self.send(next_port, packet)

        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the received distance vector is different
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
            #   broadcast the distance vector of this router to neighbors

            # Routing packet: Contains a neighbor's distance vector
            neighbor_addr = packet.src_addr
            
            try:
                neighbor_dv = json.loads(packet.content)
            except (ValueError, TypeError):
                return

            # Update what this neighbor can reach
            self.dv[neighbor_addr] = neighbor_dv

            #Recompute paths
            self._update_routing_table()

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        self.neighbor_links[port] = (endpoint, cost)
        self._update_routing_table()

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        if port in self.neighbor_links:
            neighbor, _ = self.neighbor_links[port]
            del self.neighbor_links[port]

            #Neighbor clean up
            if neighbor in self.dv:
                del self.dv[neighbor]

            self._update_routing_table()

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the distance vector of this router to neighbors
            # Periodic updates
            self._broadcast_dv()

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"DVrouter(addr={self.addr})"