####################################################
# DVrouter.py
# Name:
# HUID:
#####################################################

from router import Router


class DVrouter(Router):
    """Distance vector routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # add your own class fields and initialization code here

        #Links to direct neighbors
        self.links = {}

        #Distance Vector tracking
        self.dv = {self.addr: {self.addr: 0}}

        #Forwarding table
        self.forwarding_table = {}

    def _update_routing_table(self):
        """Recalculate the minimum costs and update the forwarding table using Bellman-Ford."""
        old_dv_self = self.dv.get(self.addr, {}).copy()

        # Reset our own vector, but we always know the cost to ourselves is 0
        self.dv[self.addr] = {self.addr: 0}
        new_forwarding_table = {}

        # Find all possible destinations known to this router or any neighbor
        all_destinations = set(self.dv.keys())

        for dst in all_destinations:
            if dst == self.addr:
                continue

            min_cost = float('inf')
            best_port = None

            # Check costs through each of our directly connected neighbor links
            for port, (neighbor, link_cost) in self.links.items():
                # If the neighbor knows a path to the destination
                if dst in self.dv and neighbor in self.dv[dst]:
                    cost_through_neighbor = link_cost + self.dv[dst][neighbor]
                    if cost_through_neighbor < min_cost:
                        min_cost = cost_through_neighbor
                        best_port = port

            # If a valid path is found, update our vector and forwarding table
            if min_cost < float('inf'):
                self.dv[self.addr][dst] = min_cost
                new_forwarding_table[dst] = best_port

        # Check if our own distance vector changed. If so, broadcast to neighbors.
        if self.dv[self.addr] != old_dv_self:
            self.forwarding_table = new_forwarding_table
            self._broadcast_dv()

    def _broadcast_dv(self):
        """Send the current router's distance vector to all connected neighbors."""
        # The packet payload is just our own distance vector dictionary: {dst: cost}
        packet_content = self.dv[self.addr]

        for port in self.links.keys():
            # Create a routing packet
            from packet import Packet
            pkt = Packet(kind=Packet.ROUTING, src_addr=self.addr, dst_addr=None, content=packet_content)
            self.send(port, pkt)

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            # send packet based on forwarding table, e.g., self.send(port, packet)

            # Forward it along if we have a route
            if packet.dst_addr in self.forwarding_table:
                next_port = self.forwarding_table[packet.dst_addr]
                if next_port is not None:
                    self.send(next_port, packet)

        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the received distance vector is different
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
            #   broadcast the distance vector of this router to neighbors

            # Routing packet: Contains a neighbor's distance vector
            neighbor_addr = packet.src_addr
            neighbor_dv = packet.payload

            # Update what this neighbor can reach
            for dst, cost in neighbor_dv.items():
                if dst not in self.dv:
                    self.dv[dst] = {}
                self.dv[dst][neighbor_addr] = cost

            # Remove destinations this neighbor no longer advertises
            for dst in list(self.dv.keys()):
                if dst != self.addr and neighbor_addr in self.dv[dst] and dst not in neighbor_dv:
                    del self.dv[dst][neighbor_addr]

            #Recompute paths
            self._update_routing_table()

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        self.links[port] = (endpoint, cost)
        self._update_routing_table()

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        if port in self.links:
            neighbor, _ = self.links[port]
            del self.links[port]

            #Neighbor clean up
            for dst in list(self.dv.keys()):
                if neighbor in self.dv[dst]:
                    del self.dv[dst][neighbor]

            self._update_routing_table()

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the distance vector of this router to neighbors
            # Periodic updates
            self._broastcast_dv()

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"DVrouter(addr={self.addr}, table={self.forwarding_table})"