####################################################
# LSrouter.py
# Name:
# HUID:
#####################################################

from router import Router


class LSrouter(Router):
    """Link state routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        self.forwarding_table = {self.addr: None}
        self.neighbors = {}
        self.graph = {}
        self.seq = {}
        self.my_seq = 0
        pass


    def broadcast(self):
        """ham thong bao trang thai lien ket cua minh cho danh sach cac neighbors"""
        import json
        from packet import Packet
        self.my_seq += 1
        local_links = {endpoint: cost for port, (endpoint, cost) in self.neighbors.items()}

        data = {"origin" : self.addr, "seq": self.my_seq, "links": local_links}

        for port, (endpoint, cost) in self.neighbors.items():
            pack = Packet(Packet.ROUTING, src_addr=self.addr, dst_addr=endpoint)
            pack.content = json.dumps(data)
            self.send(port, pack)

    def dijkstra(self):
        """thuat toan dijkstra tim duong di ngan nhat"""
        distance = {self.addr: 0}
        pre = {}
        unvisited = set(self.neighbors.keys())

        for node in self.graph:
            for neighbor in self.graph[node]:
                unvisited.add(neighbor)

        for node in unvisited:
            if node != self.addr:
                distance[node] = float('inf')

        while unvisited:
            curr_node = min(unvisited, key= lambda node: distance.get(node, float('inf')))

            if distance[curr_node] == float("inf"):
                break
            unvisited.remove(curr_node)

            if curr_node in self.graph:
                for neighbor, cost in self.graph[curr_node].items():
                    new_distance = distance[curr_node] + cost
                    if new_distance < distance.get(neighbor, float('inf')):
                        distance[neighbor] = new_distance
                        pre[neighbor] = curr_node

        new_forwarding_table = {self.addr: None}

        for d in distance:
            if d == self.addr or distance[d] == float("inf"):
                continue

            curr = d
            while pre.get(curr) and pre[curr] != self.addr:
                curr = pre[curr]
            for port, (endpoint, cost) in self.neighbors.items():
                if endpoint == curr:
                    new_forwarding_table[d] = port
                    break

            self.forwarding_table = new_forwarding_table

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            if packet.dst_addr in self.forwarding_table:
                next_port = self.forwarding_table[packet.dst_addr]
                if next_port is not None:
                    self.send(next_port, packet)

            pass
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the sequence number is higher and the received link state is different
            #   update the local copy of the link state
            #   update the forwarding table
            #   broadcast the packet to other neighbors
            import json
            data = json.loads(packet.content)
            origin = data["origin"]
            seq = data["seq"]
            links = data["links"]

            if origin in self.seq and seq <= self.seq[origin]:
                return

            self.seq[origin] = seq
            self.graph[origin] = links

            self.dijkstra()

            for pack_out in self.neighbors:
                if pack_out != port:
                    self.send(pack_out, packet)

            pass

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        self.neighbors[port] = (endpoint, cost)

        if self.addr not in self.graph:
            self.graph[self.addr] = {}
        self.graph[self.addr][endpoint] = cost
        self.dijkstra()
        self.broadcast()

        pass

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        if port in self.neighbors:
            endpoint, _ = self.neighbors[port]
            del self.neighbors[port]

            if self.addr in self.graph and endpoint in self.graph[self.addr]:
                del self.graph[self.addr][endpoint]
        self.dijkstra()
        self.broadcast()
        pass

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the link state of this router to all neighbors
            self.broadcast()
            pass

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"LSrouter(addr={self.addr})"
